fields:
  - description
keywords:
  - abbatoir
  - animal
  - bull
  - canine
  - cat
  - cattle
  - chicken
  - cow
  - dog
  - duck
  - farm
  - feline
  - geese
  - goat
  - goose
  - hen
  - kitten
  - livestock
  - pig
  - poultry
  - puppies
  - puppy
  - swine
  - turkey
